### ISSUE TITLE
Error when launching master_server.py

### ISSUE THREAD

**Issue by TheShah18** [sepalani/MH3SP#12]
Yes, I have installed Twisted for Python 2.7 and I'm using the correctly patched .ISO file of the game still with the same error

Here's an example code:

[2021-10-05 19:29:23 | AdminPage] adminpageconf.json not found. Admin page will not be available.
[2021-10-05 19:29:24 | GamespyDatabase] [xSzlGrzi] STARTING: CREATE TABLE IF NOT EXISTS users (profileid INT, userid TEXT, password TEXT, gsbrcd TEXT, email TEXT, uniquenick TEXT, pid TEXT, lon TEXT, lat TEXT, loc TEXT, firstname TEXT, lastname TEXT, stat TEXT, partnerid TEXT, console INT, csnum TEXT, cfc TEXT, bssid TEXT, devname BLOB, birth TEXT, gameid TEXT, enabled INT, zipcode TEXT, aim TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [xSzlGrzi] DONE: Took 0.000999927520752 real time / 0.0014264 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [INzlIy7N] STARTING: CREATE TABLE IF NOT EXISTS sessions (session TEXT, profileid INT, loginticket TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [INzlIy7N] DONE: Took 0.0 real time / 0.000258 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [hDUfHKVF] STARTING: CREATE TABLE IF NOT EXISTS buddies (userProfileId INT, buddyProfileId INT, time INT, status INT, notified INT, gameid TEXT, blocked INT)
[2021-10-05 19:29:24 | GamespyDatabase] [hDUfHKVF] DONE: Took 0.0 real time / 0.0003439 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [7pzCosHU] STARTING: CREATE TABLE IF NOT EXISTS pending_messages (sourceid INT, targetid INT, msg TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [7pzCosHU] DONE: Took 0.0 real time / 0.000291 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [X1KjMkxC] STARTING: CREATE TABLE IF NOT EXISTS gamestat_profile (profileid INT, dindex TEXT, ptype TEXT, data TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [X1KjMkxC] DONE: Took 0.000999927520752 real time / 0.0003557 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [ZNwvQcJx] STARTING: CREATE TABLE IF NOT EXISTS gameinfo (profileid INT, dindex TEXT, ptype TEXT, data TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [ZNwvQcJx] DONE: Took 0.0 real time / 0.0002474 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [QxfsfNmX] STARTING: CREATE TABLE IF NOT EXISTS nas_logins (userid TEXT, authtoken TEXT, data TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [QxfsfNmX] DONE: Took 0.0 real time / 0.0002315 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [1DSwaBrK] STARTING: CREATE TABLE IF NOT EXISTS banned (gameid TEXT, ipaddr TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [1DSwaBrK] DONE: Took 0.0 real time / 0.0002733 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [eHeutVEK] STARTING: CREATE TABLE IF NOT EXISTS pending (macadr TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [eHeutVEK] DONE: Took 0.00100016593933 real time / 0.0002596 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [OAbyNFWw] STARTING: CREATE TABLE IF NOT EXISTS registered (macadr TEXT)
[2021-10-05 19:29:24 | GamespyDatabase] [OAbyNFWw] DONE: Took 0.0 real time / 0.0002547 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [r9FF8J8G] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS gamestatprofile_triple ON gamestat_profile(profileid,dindex,ptype)
[2021-10-05 19:29:24 | GamespyDatabase] [r9FF8J8G] DONE: Took 0.0 real time / 0.0003031 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [BO7GJiqk] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS users_profileid_idx ON users (profileid)
[2021-10-05 19:29:24 | GamespyDatabase] [BO7GJiqk] DONE: Took 0.000999927520752 real time / 0.0003743 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [n0ox3b1v] STARTING: CREATE INDEX IF NOT EXISTS users_userid_idx ON users (userid)
[2021-10-05 19:29:24 | GamespyDatabase] [n0ox3b1v] DONE: Took 0.00100016593933 real time / 0.0003748 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [cuee3y0D] STARTING: CREATE INDEX IF NOT EXISTS pending_messages_targetid_idx ON pending_messages (targetid)
[2021-10-05 19:29:24 | GamespyDatabase] [cuee3y0D] DONE: Took 0.000999927520752 real time / 0.0004257 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [lbgivvHx] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS sessions_session_idx ON sessions (session)
[2021-10-05 19:29:24 | GamespyDatabase] [lbgivvHx] DONE: Took 0.0 real time / 0.0002809 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [8gl8gk0h] STARTING: CREATE INDEX IF NOT EXISTS sessions_loginticket_idx ON sessions (loginticket)
[2021-10-05 19:29:24 | GamespyDatabase] [8gl8gk0h] DONE: Took 0.0 real time / 0.000316 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [5Wvv83ri] STARTING: CREATE INDEX IF NOT EXISTS sessions_profileid_idx ON sessions (profileid)
[2021-10-05 19:29:24 | GamespyDatabase] [5Wvv83ri] DONE: Took 0.0 real time / 0.0003574 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [u6PzZW6V] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS nas_logins_authtoken_idx ON nas_logins (authtoken)
[2021-10-05 19:29:24 | GamespyDatabase] [u6PzZW6V] DONE: Took 0.0 real time / 0.0003774 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [lWOJuMvX] STARTING: CREATE INDEX IF NOT EXISTS nas_logins_userid_idx ON nas_logins (userid)
[2021-10-05 19:29:24 | GamespyDatabase] [lWOJuMvX] DONE: Took 0.0 real time / 0.0004118 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [1FkQ0nvS] STARTING: CREATE INDEX IF NOT EXISTS buddies_userProfileId_idx ON buddies (userProfileId)
[2021-10-05 19:29:24 | GamespyDatabase] [1FkQ0nvS] DONE: Took 0.0 real time / 0.0003361 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [QWiZrPmy] STARTING: CREATE INDEX IF NOT EXISTS buddies_buddyProfileId_idx ON buddies (buddyProfileId)
[2021-10-05 19:29:24 | GamespyDatabase] [QWiZrPmy] DONE: Took 0.0 real time / 0.0003736 processor time
[2021-10-05 19:29:24 | GamespyDatabase] [qVs5wZ6A] STARTING: CREATE INDEX IF NOT EXISTS gamestat_profile_profileid_idx ON gamestat_profile (profileid)
[2021-10-05 19:29:24 | GamespyDatabase] [qVs5wZ6A] DONE: Took 0.0 real time / 0.0004664 processor time
[2021-10-05 19:29:24 | GamespyBackendServer] Started server on 127.0.0.1:27500...
[2021-10-05 19:29:24 | GameSpyProfileServer] Now listening for connections on 0.0.0.0:29900...
[2021-10-05 19:29:24 | GameSpyPlayerSearchServer] Now listening for player search connections on 0.0.0.0:29901...
[2021-10-05 19:29:24 | GameSpyGamestatsServer] Now listening for connections on 0.0.0.0:29920...
[2021-10-05 19:29:24 | AdminPage] Now listening for connections on port 9009...
[2021-10-05 19:29:24 | RegisterPage] Now listening for connections on port 9998...
[2021-10-05 19:29:24 | StorageServer] Checking for and creating database tables...
[2021-10-05 19:29:24 | GameStatsServerHttp] Now listening for connections on 127.0.0.1:9002...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Joshua Shah\Desktop\MHTri Private Server\dwc_network_server_emulator-master\nas_server.py", line 269, in start
    httpd = NasHTTPServer(address, NasHTTPServerHandler)
  File "C:\Python27\lib\SocketServer.py", line 420, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

[2021-10-05 19:29:24 | Dls1Server] Now listening for connections on 127.0.0.1:9003...
[2021-10-05 19:29:24 | GameSpyQRServer] Server is now listening on 0.0.0.0:27900...
[2021-10-05 19:29:24 | GameSpyServerBrowserServer] Now listening for connections on 0.0.0.0:28910...
[2021-10-05 19:29:24 | GameSpyNatNegServer] Server is now listening on 0.0.0.0:27901...
[2021-10-05 19:29:24 | StorageServer] Now listening for connections on 127.0.0.1:8000...

Hope this helps and someone will be able to provide a solution
Cheers!

**Comment by sepalani** [comment]
That's not MH3SP `master_server.py` but [AltWFC's](https://github.com/barronwaffles/dwc_network_server_emulator).

> Exception in thread Thread-7:
Traceback (most recent call last):
File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
self.run()
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Users\Joshua Shah\Desktop\MHTri Private Server\\**dwc_network_server_emulator-master\nas_server.py**", line 269, in start
httpd = NasHTTPServer(address, NasHTTPServerHandler)
File "C:\Python27\lib\SocketServer.py", line 420, in init
self.server_bind()
File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "C:\Python27\lib\SocketServer.py", line 434, in server_bind
self.socket.bind(self.server_address)
File "C:\Python27\lib\socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 10013] **An attempt was made to access a socket in a way forbidden by its access permissions**

You don't have the permission to create a socket on that port and might be related to:
 - https://github.com/sepalani/MH3SP/wiki/Setup#start-the-server 

Closing this issue as this server isn't part of this repository.

**Comment by sepalani** [comment]
Don't let the log fool you, the error came from **nas_server.py** (on port 80, I believe) not `GameStatsServerHttp` which was successful:
 >  [2021-10-05 19:29:24 | GameStatsServerHttp] Now listening for connections on 127.0.0.1:9002...
